### PR TITLE
 Merge columns

### PR DESCRIPTION
**Pull request by ewojtach**

### CODE REVIEW

**Comment by ewojtach** [comment]
test temporary ignored, as dropping column is not supported in BigQuery currently.
Merge implementation for bigquery is added and ready to run when drops will be supported.

**Review by bimission — COMMENTED** [review]
Hej Ewa, why not to modify SQL generator for MergeColumn instead od Merge Column Change? 

I would expect it works as updated .. SQL generator where we just add where 1=1 when .. where expression is not specified.

**Comment by ewojtach** [comment]
> ergeColumn i

thanks for the comment - I haven't found any MergeColumnGenerator in core liquibase implementation. Is there something like that, that I missed? Additionally, MergeColumnChange is generating sql directly in `generateStatements` method so I do not see the way it could be redefined later?

**Comment by bimission** [comment]
> thanks for the comment - I haven't found any MergeColumnGenerator in core liquibase implementation. Is there something like that, that I missed? Additionally, MergeColumnChange is generating sql directly in `generateStatements` method so I do not see the way it could be redefined later?

Ok - od there is no generator then pleased neglect my comment. IT is in general strange that all changes can be controller by overwriting corresponding SQL generator class and this one not. Thanks for finding this workaround!

**Review by karticn-google — APPROVED** [review]
LGTM

**Pull request merged**
